### ISSUE TITLE
Install tesselate_building in dotnet

### ISSUE THREAD

**Issue by sehHeiden** [bertt/tesselate_building#3]
I want to install tesselate_building for dotnet 6.0.

1. I installed dotnet 6.0
2. Reboot
3. dotnet --version: 6.0.408
4. ```dotnet tool install -g tesselate_building``` or ```dotnet tool install --global tesselate_building --version 0.2.0```
Error:

The package cannot be resolved. (Error message in local language, so I did not add it)
As possible causes:
- beta versions
- NuGet connection failure
- wrong names
are mentioned.

I tried to use docker instead:

1. loaded the repo
2. cd to src
3. ```docker build -t bertt/tesselate_building .```

Error message:

> failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount350989808/Dockerfile: no such file or directory

- Should I use another version of dotnet, or source, build form source (how-to?)?
- Could you add a desciption for usage with docker?

EDIT:
I just checked. I is a general problem with dotnet tools

**Comment by sehHeiden** [comment]
Worked with: `dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources tesselate_building`.

**Comment by bertt** [comment]
ok think this can be closed
