### ISSUE TITLE
Getting pg2b3dm with own colours -> colours too dark

### ISSUE THREAD

**Issue by sehHeiden** [bertt/tesselate_building#5]
I tried the procedure in the [getting started guide](https://github.com/Geodan/pg2b3dm/blob/master/getting_started.md) but used my own colours White (FFFFFF) and light Gray (A7A7A7).

Aim: Wanted to get some White and Gray buildings, with some shadows perhaps.
Problem: The colours got *much* to dark. White was turned into middle gray and the light gray turned into dark gray.

# Versions
- pgsb3dm -> 1.5.3
- tesselate_building -> 0.2.0.0

**Comment by bertt** [comment]
yeah good point, it's something with the light if I remember well... Anyway I asked in on the Cesium forum https://community.cesium.com/t/white-3d-tiles-very-dark/26208

**Comment by bertt** [comment]
fixed it in release 0.2.1 of this tool (by using 0 for MetallicRougness instead of the default) see https://bertt.github.io/cesium_issues/dark/fixed/

**Comment by sehHeiden** [comment]
I tested it new version 0.2.1
This fixed the problem.
