### ISSUE TITLE
Idea: Using ST_Extrude instead 

### ISSUE THREAD

**Issue by mittermichal** [bertt/tesselate_building#8]
since all buildings are sharing roof,wall and floor color, could this whole project be replaced with just calling ST_Extrude from PostGIS SFCFAL extension and given that it adds bottom and top 1st https://gitlab.com/sfcgal/SFCGAL/-/blob/master/src/algorithm/extrude.cpp?ref_type=heads#L134-160
then pg2b3dm could have special switch to assign specific color to 1st,2nd polygon during conversion
not sure if its actually possible just an idea

**Comment by bertt** [comment]
yeah it's basically the same as st_extrude whats happening here. I see st_extrude generates a polyhedralsurface, with

- polygon 1: floor
- polygon 2: roof
- polygon 3 ..n: walls

Which can be used directly in pg2b3dm.

A bit complication can come from the storeys, then we want to extrude from z=10 to z=20 for example.

**Comment by bertt** [comment]
Looking at it a bit more, I don't think it's worth to add another round trip to the database per building for such a simple function. Closing this issue.

**Comment by mittermichal** [comment]
another round trip? the idea is to create sql procedure which would create extruded geometry and fill up shaders column and user would have to just call the procedure e.g.
```sql
Tesselate_Buildings(delaware_buildings,geom,geom_triangle,style);
```
I expect it would be faster than iterating through rows and generating the geometry in C#. It should be less code to maintain even with storeys logic, but on the other hand I suspect it would be probably harder to add more details with just using PostGIS functions, like 3D roof or windows or balconies.
